Controllers/AdminController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MarquezBouzoDanielExamen1.Controllers
{
    public class AdminController : Controller
    {
        // GET: AdminController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AdminController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdminController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/CriptomonedasController.cs
using MarquezBouzoDanielExamen1.Models;
using MarquezBouzoDanielExamen1.Models.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace MarquezBouzoDanielExamen1.Controllers
{
    public class CriptomonedasController : Controller
    {
        private readonly ICriptomonedasRepository _criptomonedasRepository;
        public CriptomonedasController(ICriptomonedasRepository criptomonedasRepository)
        {
            _criptomonedasRepository = criptomonedasRepository;
        }
        // GET: CriptomonedasController
        public async Task<ActionResult> IndexAsync()
        {
            if (CheckLogin())
            {
                var data = await _criptomonedasRepository.GetAll();
            return View("Index", data);
            }
            return View(GlobalVar.LoginView);
        }

        // GET: CriptomonedasController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            if (CheckLogin())
            {
                var data = await _criptomonedasRepository.GetById(id);
            return View("Edit", data);
            }
            return View(GlobalVar.LoginView);
        }

        // GET: CriptomonedasController/Create
        public async Task<ActionResult> Create(int id)
        {
            if (CheckLogin())
            {
                var data = await _criptomonedasRepository.GetById(id);
            return View("Create", data);
                }
                return View(GlobalVar.LoginView);
            }

        // POST: CriptomonedasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Criptomonedas criptomonedas)
        {
            if (CheckLogin())
            {
                _criptomonedasRepository.Save(criptomonedas);
                var data = await _criptomonedasRepository.GetAll();
                return View("Index",data);
            }
                return View(GlobalVar.LoginView);
        }

        // POST: CriptomonedasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditFAsync(Criptomonedas c)
        {
            if (CheckLogin()) { 
                await _criptomonedasRepository.Edit(c);
            return RedirectToAction("Index");
            }
            return View(GlobalVar.LoginView);

        }

        // GET: CriptomonedasController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            if (CheckLogin())
            {

            var data = await _criptomonedasRepository.GetById(id);
            return View("Delete", data);
            }
            return RedirectToAction("Index");
        }

        // POST: CriptomonedasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Criptomonedas c)
        {
            try
            {
                _criptomonedasRepository.Delete(c);
                var data = await _criptomonedasRepository.GetAll();
                return View("Index", data);
            }
            catch
            {
                return View();
            }
        }
        public async Task Carrito(int id)
        {
            var cripto = await _criptomonedasRepository.GetById(id);

            if (HttpContext.Session.GetString("Cartera") != null)
            {
                string arrayBytes = HttpContext.Session.GetString("Cartera");
                var cartera = JsonSerializer.Deserialize<List<Criptomonedas>>(arrayBytes);
                cartera.Add(cripto);
            } else
            {
                var cartera = new List<Criptomonedas>();
                cartera.Add(cripto);
                string jsonString = JsonSerializer.Serialize(cartera);
                HttpContext.Session.SetString("Cartera", jsonString);
            }
        }
        public bool CheckLogin()
        {
            return HttpContext.Session.GetString("Logeado") == null ? false : true;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarquezBouzoDanielExamen1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MarquezBouzoDanielExamen1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MarquezBouzoDanielExamen1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (GlobalVar.loggedUser != null) {
                            if (GlobalVar.loggedUser.es_administrador == 1)
                                {  
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Administrador de criptomonedas</a>
                                </li>
                                }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Criptomonedas" asp-action="Index">Lista de criptomonedas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MarquezBouzoDanielExamen1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>